### ISSUE TITLE
Documentation issue: misaligned SessionManager docs

### ISSUE THREAD

**Issue by markwoodward23** [kinde-oss/kinde-typescript-sdk#12]
### Prerequisites

- [X] I have searched the repository’s issues and the [Kinde community](https://thekindecommunity.slack.com/archives/C057M2BQ6LV) to ensure my documentation issue isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/489e2ca9c3307c2b2e098a885e22f2239116394a/CONTRIBUTING.md)
- [X] I agree to the terms in the [code of conduct](https://github.com/kinde-oss/.github/blob/489e2ca9c3307c2b2e098a885e22f2239116394a/CODE_OF_CONDUCT.md)

### How can we improve the docs or what is missing?

https://kinde.com/docs/developer-tools/typescript-sdk/#check-if-user-authenticated suggests you can pass in the `req` request to the `isAuthenticated` function exposed by the client, but this only works if https://kinde.com/docs/developer-tools/typescript-sdk/#check-if-user-authenticated is followed (ie a session manager exists on the request).

It'd be great to align these! 

### Provide extra context, such as what you were trying to do and your requirements

I was trying to check if a user was authenticated or not, following the docs on the website, and had to dig into the GitHub instead.

**Comment by DaveOrDead** [comment]
Thanks @markwoodward23 - quite right and great spot. We'll get these synced up

**Comment by coel** [comment]
Thank you for raising this @markwoodward23.  We've updated the documentation to use an explicit `sessionManager` to try and make it clearer this is something required.  We hope to provide more session manager implementations to help users get started.
