### ISSUE TITLE
Documentation issue: (`SessionManager` section is out of date after migration to async functions)

### ISSUE THREAD

**Issue by atifcppprogrammer** [kinde-oss/kinde-typescript-sdk#14]
### Prerequisites

- [X] I have searched the repository’s issues and the [Kinde community](https://thekindecommunity.slack.com/archives/C057M2BQ6LV) to ensure my documentation issue isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### How can we improve the docs or what is missing?

With the codebase being migrated to using async functions post #13, it is important that the the `SessionManager` section in the `README` reflect this. This seemed to be missed out by #13.

### Provide extra context, such as what you were trying to do and your requirements

Just noticed this :smile: 

### If the docs page already exists, please provide a link

https://kinde.com/docs/developer-tools/typescript-sdk/

**Comment by DaveOrDead** [comment]
Thanks so much for the PR @atifcppprogrammer - you're on 🔥 at the moment :)
