### ISSUE TITLE
Documentation issue: ENV template uses URI instead of URL

### ISSUE THREAD

**Issue by LiamGallagher737** [kinde-oss/kinde-typescript-sdk#17]
### Prerequisites

- [X] I have searched the repository’s issues and the [Kinde community](https://thekindecommunity.slack.com/archives/C057M2BQ6LV) to ensure my documentation issue isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### How can we improve the docs or what is missing?

The Typescript SDK docs show the following when explain the env variables to setup.
```env
KINDE_REDIRECT_URI=http://localhost:3000/callback
```
But when creating the client it uses URL instead of URI
```ts
const clientOptions: ACClientOptions = {
    // ...
    redirectURL: process.env.KINDE_REDIRECT_URL
};
```
The env should be changed to URL
```diff
- KINDE_REDIRECT_URI=http://localhost:3000/callback
+ KINDE_REDIRECT_URL=http://localhost:3000/callback
```

### Provide extra context, such as what you were trying to do and your requirements

Setting up Kinde for my app, got type error that `string | undefined` couldn't be used for a field of type string. Noticed incorrect env name.

### If the docs page already exists, please provide a link

https://kinde.com/docs/developer-tools/typescript-sdk/#configure-your-app

**Comment by LiamGallagher737** [comment]
Also noticed under `Login and register > Browser` in both functions it references `kinderClient` instead of `kindeClient`.
https://kinde.com/docs/developer-tools/typescript-sdk/#log-in-and-register:~:text=const%20url%20%3D%20await%20kinderClient.register()%3B

**Comment by coel** [comment]
Thank you for raising these @LiamGallagher737.  For simplicity, we've removed the `.env` part from the documentation now as it is not essential to using the SDK.  References to `kinderClient` have also been fixed now as we've reviewed the code snippets.
