### ISSUE TITLE
Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method).

### ISSUE THREAD

**Issue by fiyazbinhasan** [kinde-oss/kinde-typescript-sdk#20]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

I'm building a Qwik application. Since there is no SDK available, I'm using this SDK. I'm getting the following exception when trying to exchange an authorization code for a token,

```
{
	"error": "invalid_client",
	"error_description": "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)."
}
```

My payload for the token request URL looks ok. I'm not sure what is causing this issue:

![image](https://github.com/kinde-oss/kinde-typescript-sdk/assets/6568968/a37cfe4d-2edf-41ac-80f9-1291d0b4874a)

![image](https://github.com/kinde-oss/kinde-typescript-sdk/assets/6568968/4475cf9e-0ae1-43c7-8ff6-f037b6fe0c31)

### Library URL

https://github.com/kinde-oss/kinde-typescript-sdk

### Library version

2.2.0

### Operating system(s)

Windows

### Operating system version(s)

Windows 11

**Comment by coel** [comment]
Hi @fiyazbinhasan,

I take it those screenshots are from Chrome, so this is a front-end PKCE token exchange?  Can you check the type of the Application setup in Kinde?  That is, from the Kinde admin UI go to `Settings`, then `Applications` (under `Environment`).

For PKCE, the Application type should be `SPA or Mobile Application`.  Currently for type `Regular Web Application` it will expect a client secret, but one is not provided using PKCE flow.

**Comment by fiyazbinhasan** [comment]
Hello @coel, I've change it from a Regular Web Application to a SPA. Now I'm getting a new exception. Any idea?

![image](https://github.com/kinde-oss/kinde-typescript-sdk/assets/6568968/2316355e-f790-4876-b9ed-b844b8294c3a)

```
"The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
```

**Comment by coel** [comment]
G'day @fiyazbinhasan, unfortunately a bit of a tough one to debug without more information.  What are you using for the session manager?  I'm not familiar with Quik, sounds like it is designed for edge servers, which I think typically lends itself to storing in cookies as there isn't server persistence.

If there is some code, or more detailed reproduction steps you can provide, we can look into it further.

**Comment by fiyazbinhasan** [comment]
It was a configuration issue on my end.
