### ISSUE TITLE
Bug: exception raised by calling `getUserOrganizations` post ID token expiry

### ISSUE THREAD

**Issue by muhammadatif-devsinc** [kinde-oss/kinde-typescript-sdk#25]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

When the ID token expires _while the access token is still valid_, calling the `getUserOrganizations` method raises the following exception and logs out the user.

```
No authentication credential found, when requesting claim org_codes
```
The above bug can be reproduced using the following steps
- login into Kinde's dashboard and open your application settings.
- set ID token expiry for 60 seconds and that of the access token for 80 seconds.
- login in app with a user.
- wait 60 seconds once the ID token has been expired and call the `getUserOrganizations` method.

### Library URL

https://github.com/kinde-oss/kinde-typescript-sdk

### Library version

2.2.0

### Operating system(s)

Ubuntu

### Operating system version(s)

Ubuntu 20.04

**Comment by coel** [comment]
Fix published in v2.2.2
