### ISSUE TITLE
Feature request: Add expandable fields to the User type (TypeScript SDK)

### ISSUE THREAD

**Issue by askable-nic** [kinde-oss/kinde-typescript-sdk#30]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

I'm able to call `getUserData` with the expand option to return organization IDs and the response includes an `organizations`, but the return type (`User`) doesn't include that field so TypeScript complains when I try to access it.

### What solution would you like to see?

Include the expanded fields on the `User` type

It might also be helpful to update the type of `GetUserDataRequest['expand']` to a literal as opposed to `string | null`

**Comment by oliwolff1** [comment]
Hi @askable-nic,
Thanks for raising this issue.
In the latest version of the Kinde TypeScript SDK, a `User` includes the `organizations` field - see [here](https://github.com/kinde-oss/kinde-typescript-sdk/blob/8e71bdf89be3ac4d1840071952360d526e7a51a4/lib/models/User.ts#L100)

Does this solve what you are after?

**Comment by askable-nic** [comment]
Perfect, thanks!

**Comment by oliwolff1** [comment]
In that case, I will close this issue.

**Comment by oliwolff1** [comment]
In that case, I will close this issue.
