### ISSUE TITLE
Compatibility Issue with Kinde TypeScript SDK and Next.js 14

### ISSUE THREAD

**Issue by suzushi-tw** [kinde-oss/kinde-typescript-sdk#54]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

Hi, I'm encountering a compilation error when using the Kinde TypeScript SDK with Next.js 14. The error message indicates a problem with Webpack not being able to resolve certain exports from the Kinde SDK. Here's the error message I'm seeing:

```

Failed to compile.
--
12:29:52.831 |  
12:29:52.832 | ./node_modules/@kinde-oss/kinde-typescript-sdk/dist/index.js + 132 modules
12:29:52.832 | Cannot get final name for export 'AddAPIsRequestToJSON' of ./node_modules/@kinde-oss/kinde-typescript-sdk/dist/models/index.js
12:29:52.832 |  
12:29:52.834 |  
12:29:52.834 | > Build failed because of webpack errors
12:29:53.066 | Error: Command "npm run build" exited with 1


```
This issue does not occur when I downgrade Next.js to version 13.5. I've tried installing the latest versions of the Kinde TypeScript SDK (both 2.6.2 and 2.7.2), but the problem persists. I would appreciate any guidance or assistance in resolving this compatibility issue. Thank you!

### Library URL

https://github.com/kinde-oss/kinde-typescript-sdk

### Library version

2.6.2-2.7.2

### Operating system(s)

Windows

### Operating system version(s)

Windows 11 latest

**Comment by DanielRivers** [comment]
Hi @suzushi-tw, are you using typescript SDK directly in NextJS?  Is there a reason why you're not using the NextJS SDK?

**Comment by suzushi-tw** [comment]
> Hi @suzushi-tw, are you using typescript SDK directly in NextJS? Is there a reason why you're not using the NextJS SDK?

Hi, was looking for a way to logout the user manuelly, so I thought of using kindeclient. Does the nextjs sdk come with this functionality(I only saw the Logout Link component) ? Thanks in advance.

**Comment by DanielRivers** [comment]
Sure you can direct the user to the url `/api/auth/logout` and it will log them out.

**Comment by suzushi-tw** [comment]
> Sure you can direct the user to the url `/api/auth/logout` and it will log them out. 

Thank you so much !
