### ISSUE TITLE
Feature request: Webhook client

### ISSUE THREAD

**Issue by dror-weiss** [kinde-oss/kinde-typescript-sdk#57]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

I'm writing my own Webhook client and guess some of the event types based on my experimentation with the Webhooks feature (which, as of now, is still in Beta)

### What solution would you like to see?

I would like to see a Webhooks client in the SDK that will handle:
- Verification of the incoming JWT based on the organization JWK.
- Types of the various events.

**Comment by DanielRivers** [comment]
Hi @dror-weiss, great minds! This is already in planning

**Comment by dror-weiss** [comment]
@DanielRivers , any progress in this direction?

**Comment by DanielRivers** [comment]
Hi @dror-weiss ,

We have released the webhook package library. 

It can be found here: https://github.com/kinde-oss/webhook
